export const CN_LANGS_MAP: Record<string, string> = {
    A_0: "C++",
    A_1: "Java",
    A_2: "Python",
    A_3: "MySQL",
    A_4: "C",
    A_5: "C#",
    A_6: "JavaScript",
    A_7: "Ruby",
    A_8: "Bash",
    A_9: "Swift",
    A_10: "Go",
    A_11: "Python3",
    A_12: "Scala",
    A_13: "Kotlin",
    A_14: "MS SQL Server",
    A_15: "Oracle",
    A_16: "HTML",
    A_17: "Python ML",
    A_18: "Rust",
    A_19: "PHP",
    A_20: "TypeScript",
    A_21: "Racket",
    A_22: "Erlang",
    A_23: "Elixir",
};

export const CN_RESULTS_MAP: Record<string, string> = {
    A_10: "Accepted",
    A_11: "Wrong Answer",
    A_12: "Memory Limit Exceeded",
    A_13: "Output Limit Exceeded",
    A_14: "Time Limit Exceeded",
    A_15: "Runtime Error",
    A_16: "System Error",
    A_20: "Compile Error",
    A_30: "Timeout",
};
